config/routes.rb
Spn::Application.routes.draw do
	
	root :to => "pages#home"

  match '/about', :to => "pages#about"

  match '/contact', :to => "pages#contact"

  get "pages/terms"

	get "sessions/new", :as => "getstarted"

  get "pages/privacy"

  get "pages/credits"

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout", to: "sessions#destroy", :as => "signout"
  resources :identities

	

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
	validates_presence_of :age

	validates :age, :numericality => { :greater_than_or_equal_t0 => 13, :message => "You must be older than 13 to use this site" }

  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/user.rb
class User < ActiveRecord::Base	
	def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
			user.email = auth["info"]["email"]
			user.age = auth["info"]["age"]
    end
  end
	
	before_create { generate_token(:auth_token) }

	after_create :add_user_to_mailchimp



	def add_user_to_mailchimp  
		mailchimp = Hominid::API.new("323e2375482cbe3490669fc180f270ca-us1")
		list_id = mailchimp.find_list_id_by_name "Social Prayer Network"
		mailchimp.list_subscribe(list_id, self.email, {'MMERGE3' => self.name}, 'html', false, true, false, false)
	end

	def generate_token(column)
		begin 
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
	def new
    @identity = env['omniauth.identity']
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		@title = "Welcome"
  end

  def contact
		@title = "Contact Page"
  end

  def terms
		@title = "Terms of Use"
  end

  def privacy
		@title = "Privacy Policy"
  end

  def credits
		@title = "Credits"
  end

	def about
		@title = "About"
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	end

	def create
    user = User.from_omniauth(env["omniauth.auth"])
		if params[:remember_me]
			cookies.permanent[:auth_token] = user.auth_token
		else
			cookies[:auth_token] = user.auth_token
		end
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to getstarted_url, notice: "The Email or Password was wrong!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis.
  def title
    base_title = "Social Prayer Network"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end

end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/identities/new.html.erb
<h1>Register</h1>

<%= form_tag "/auth/identity/register", :id => "contactForm" do %>
  <% if @identity && @identity.errors.any? %>
    <div id="notice" class="infoMessage warning">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
    <%= label_tag :name %><%= text_field_tag :name, @identity.try(:name), :class => "input" %>

    <%= label_tag :email %><%= text_field_tag :email, @identity.try(:email), :class => "input" %>

		<%= label_tag :age %><%= text_field_tag :age, @identity.try(:age), :class => "input" %>

    <%= label_tag :password %><%= password_field_tag :password, nil, :class => "input" %>

    <%= label_tag :password_confirmation %><%= password_field_tag :password_confirmation, nil, :class => "input" %>

		<%= label_tag :remember_me %><%= check_box_tag :remember_me, 1, params[:remember_me] %>

</fieldset>
<%= submit_tag "Register", :class => "submit" %>
<% end %>

app/views/layouts/_footer.html.erb
	<div class="clear"></div>
	<div id="footerWrapper">
		<div id="footer">
			<div class="col1">
				<p class="title">Recent SocialPress News.</p>
				<ul class="component">
					<li>Neque porro quisquam est</li>
					<li>ipsum quia dolor</li>
					<li>adipisci velit</li>
					<li>modi tempora incidunt</li>
					<li>magnam aliquam</li>
					<li>enim ad minima</li>
					<li>exercitationem ullam corporis suscipit</li>
					<li>laboriosam, nisi ut aliquid</li>
				</ul>
			</div>
			
			<div class="col2">
				<p class="title">You can find us on...</p>
				<ul class="component">
					<li><a href="#">Del.icio.us</a></li>
					<li><a href="#">Mixx</a></li>
					<li><a href="#">StumbleUpon</a></li>
					<li><a href="#">Myspace</a></li>
					<li><a href="#">Facebook</a></li>
					<li><a href="#">Twitter</a></li>
					<li><a href="#">LinkedIn</a></li>
					<li><a href="#">Technorati</a></li>
				</ul>
			</div>
			
			<div class="col3">
				<div class="logo"><a href="index.html"><span>SocialPress - Clean theme for your enjoyment</span></a></div>
				<p class="bigTitle">Submit an article.</p>
				<p class="bigTitle">Spread the word to all.</p>
				<p class="bigTitle">Live <span>SOCIAL!</span></p>
			</div>
			
			<div class="clear"></div>
			<div class="footerDivider"></div>
			
			<div id="copyright">
				<div class="left"></div>
				<div class="right"></div>
				<div id="copyrightContent">
					&copy; Copyright 2009 Your Name. All Rights Reserved. Conforms to W3C Standard  <a href="http://validator.w3.org/check?uri=referer" title="Validate XHTML">XHTML</a> &amp;
					<a title="Validate CSS" href="http://jigsaw.w3.org/css-validator/check/referer"> CSS</a>
				</div>
			</div><!--[END] #copyright -->
		</div><!--[END]#footer-->
	</div><!--[END]#footerWrapper-->
</body>
</html>

app/views/layouts/_header.html.erb
	<%= stylesheet_link_tag 'reset', :media => 'screen' %>
	<%= stylesheet_link_tag 'default', :media => 'screen' %>
	<%= stylesheet_link_tag 'typography', :media => 'screen' %>

  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag "template/jquery.scrollTo-1.3.3.js", "template/jquery.localscroll-1.2.5.js", "template/jquery.serialScroll-1.2.1.js", "template/coda-slider.js" %>
  <%= csrf_meta_tag %>
	<!--[if IE]>	
		<%= javascript_include_tag "template/DD_belatedPNG_0.0.7a-min.js" %>
		<script>	 
			DD_belatedPNG.fix('.navShadow');	 
			DD_belatedPNG.fix('.logo a');	 
		</script>
	<![endif]-->

	<!--[if IE 6]>
		<%= stylesheet_link_tag 'ie6Styles', :media => 'screen' %>	
	<![endif]-->

	<!--[if IE 7]>
		<%= stylesheet_link_tag 'ie7', :media => 'screen' %>	
	<![endif]-->

app/views/layouts/_menu.html.erb
			<div id="topNav">
				<ul class="topNavigation">
					<li><%= link_to "HOME", root_path %></li>
					<li><% if current_user %><%= link_to "SIGN OUT", signout_path %> <% else %><%= link_to "LOGIN / REGISTER", getstarted_path %><% end %></li>
					<li><a href="#">GET PRAYER</a></li>
					<li><%= link_to "ABOUT US", about_path %></li>
					<li><%= link_to "CONTACT US", contact_path %></li>
				</ul>
			</div>
		</div><!--[END]#header-->
		
		<div id="navigation">			
			<ul class="mainNav">
				<li class="first"><% if current_user %><%= link_to "SIGN OUT", signout_path %> <% else %><%= link_to "Sign in with Twitter", "/auth/twitter" %><% end %></li>
				<li><%= link_to "Create an account", "/auth/identity/register" %></li>
				<li><%= link_to "login", "/auth/identity" %></li>				
				<li><a href="#">Web Design</a></li>
				<li><a href="#">Tutorials</a></li>
				<li><a href="#">Programming</a></li>				
			</ul>
		</div><!--[END]#navigation-->


  

app/views/layouts/_right-column.html.erb
		<div id="rightCol">
			<!--Search module -->
			<div id="searchModule">
				<div class="content">
					<p class="title"><span>Search</span> Our Site</p>
					<form id="searchForm" action="" method="post">
						<input type="text" name="searchBox" class="input" id="searchBox" />
						<input type="submit" id="submit" class="submit" value="" />
					</form>
				</div>
			</div>
			<!--[END}Search module -->
			
			<!--Twitter module -->
			<% if current_user %>
			<div class="module">
				<div class="moduleTop"></div>
				<div class="content">
					<p class="title"><span>Welcome</span> <%= current_user.name %></p>
					<ul class="twitter">
						<li>Location: <%= current_user.city %> <%= current_user.state %></li>
						<li><%= link_to "Sign Out", signout_path %></li>
					</ul>
					
				</div>
				<div class="moduleBottom"></div>				
			</div>
			<% end %>
			<!--[END}Twitter module -->
			
			<!--Popular Posts -->
			<div class="module">
				<div class="moduleTop"></div>
				<div class="content">
					<p class="title"><span>Popular</span> Articles</p>
					<ul class="popularPosts">
						<li><a href="#">Learn to code PSD to html hand  2 mins ago</a></li>
						<li><a href="#">Take photoshop to the next level 1 hour ago</a></li>
						<li><a href="#">Balance your budget and pay off credit cards 3 hours ago</a></li>
						<li><a href="#">Gas is the devil - a look at alternative fueling 4 hours ago</a></li>
					</ul>
				</div>
				<div class="moduleBottom"></div>				
			</div>
			<!--[END]Popular Posts -->
			
			<!--Categories -->
			<div class="module">
				<div class="moduleTop"></div>
				<div class="content">
					<p class="title"><span>Popular</span> Categories</p>
					<ul class="popularCategores">
						<li><a href="#">Photoshop</a></li>
						<li><a href="#">Freebies</a></li>
						<li><a href="#">Tutorials</a></li>
						<li><a href="#">Photography</a></li>
						<li><a href="#">World News</a></li>
						<li><a href="#">Social Media</a></li>
					</ul>
				</div>
				<div class="moduleBottom"></div>				
			</div>
			<!--[END]Categories -->			
			
			<!--Newsletter module -->
			<div class="module">
				<div class="moduleTop"></div>
				<div class="content">
					<p class="title signup"><span>SignUp</span> For Our Newsletter</p>
					<p class="subtext">Enter your email address to subscribe to our newsletter</p>
					<form id="signupForm" action="" method="post">
						<input type="text" name="searchBox" class="input" id="signupBox" />
						<input type="submit" class="submit" value="" />
						<div class="clear"></div>
					</form>
				</div>
				<div class="moduleBottom"></div>
			</div>
			<!--[END]Newsletter module -->
		
		</div><!--[END]#rightCol-->	

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">  
<html xmlns="http://www.w3.org/1999/xhtml">  
<head> 
  <title><%= title %></title>
	<%= render 'layouts/header' %>
</head>
<body id="contactPage">
	<div id="wrapper">
		<div id="header">	
			<div id="logoWrapper">
				<div class="logo"><%= link_to "", root_path %></div>
			</div>
			<%= render 'layouts/menu' %>
		
		
		
			
		
		<div id="leftCol">
			<% if flash[:notice] %>
				<div id="notice" class="infoMessage <% if flash[:error] %>error<% end %><% if flash[:notice] %>warning<% end %>"><%= flash[:notice] %></div><br /><br />
				<script type="text/javascript">
					setTimeout("new Effect.Fade('notice');", 15000)
				</script>
			<% end %>

			<%= yield %>	
		</div><!--[END]#leftCol-->


				
		<%= render 'layouts/right-column' %>



		<div class="clear"></div>
	</div><!--[END] #wrapper -->

<%= render 'layouts/footer' %>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Contact the Social Prayer Network</p>

app/views/pages/credits.html.erb
<h1>Pages#credits</h1>
<p>Find me in app/views/pages/credits.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<p>Welcome to the prayer revolution!</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>